### ISSUE TITLE
allow setting a default font

### ISSUE THREAD

**Issue by ammarbinfaisal** [ammarbinfaisal/terminal-timer#3]
allow setting a default font by the command line interface user.
configstore can be used for this.

**Comment by mgs96** [comment]
I will try this!

**Comment by mgs96** [comment]
Hello @ammarbinfaisal! I apologize for not reporting, I had a busy week, I'm planning to tackle it this weekend, but If I can't I'll let you know, of course, this is open to anybody!

**Comment by ammarbinfaisal** [comment]
thanks a lot buddy, but I completed this.
i understand!! you're a professional  :+1: and I am just a kid

**Comment by ammarbinfaisal** [comment]
there's another issue which needs help you can solve that till I am busy with gci.
