### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by victorperin** [ammarbinfaisal/terminal-timer#4]
Hello,

Could be awesome to have a better README for the project, describing how it works, how to install and how to help.

**Comment by ammarbinfaisal** [comment]
Hi Victor,
I haven't published this anywhere right now so it doesn't have a proper readme.
Still I have made some changes, which you can see.

**Comment by ammarbinfaisal** [comment]
can you plz help me in #1? not sure about whether this can be useful in other apps

**Comment by ammarbinfaisal** [comment]
sorry i meant #1
